version: "3.5"

services:
  database:
    build: ./database
    image: quizzer-category-db
    container_name: quizzer-category-db
    volumes:
      - quizzer-category-db-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    networks:
      - quizzer-network
  service:
    build: .
    image: quizzer-category-service
    container_name: quizzer-category-service
    depends_on:
      - database
    ports:
      - 8200:8200
    networks:
      - quizzer-network
    environment:
      DATABASE_HOST: quizzer-category-db
      DATABASE_PORT: 5432
volumes:
  quizzer-category-db-data:

networks:
  quizzer-network:
    name: "quizzer-network"
    external: true

