version: "3.8"

services:
  database:
    build: ./database
    image: quizzer_category_db
    container_name: quizzer_category_db
    volumes:
      - quizzer_category_db_data:/var/lib/psql
    ports:
      - 5555:5432
    networks:
      - quizzer_category_network
  service:
    build: .
    image: quizzer_category_service
    container_name: quizzer_category_service
    ports:
      - 8080:8080
    networks:
      - quizzer_category_network

volumes:
  quizzer_category_db_data:

networks:
  quizzer_category_network:
    driver: bridge
